- src/lib/layouts/Chatbar.svelte
Wires up markdown settings for chatbar
> feat(settings:) wireup markdown setting

- src/lib/elements/Input/Input.svelte
Syncs the markdown editors value with the input
> Sync markdown value to value

- src/lib/elements/Input/Input.svelte
Fixes markdown input not sending. for real now
> fix markdown sending

- src/lib/lang/index.ts
- src/routes/chat/+page.svelte
- src/routes/files/+page.svelte
Adds drag/drop to files and chat page. Layout taken from native uplink.
Currently only the ui functionality due to missing warp integration
> add file drag drop for files and chat

- src/lib/components/PinInput.svelte
- src/lib/elements/Button.svelte
- src/routes/auth/unlock/+page.svelte
- Add data-cy test attributes into Pin Input for testing on the cypress repository 
- Still researching on how to get rid of data-cy attributes when building for something different than test
> update(test): add test attributes for pin input

- .github/workflows/add-conflicts-label.yml
- .github/workflows/add-label.yml
- .github/workflows/assigned-label.yml
- .github/workflows/avoid-typos.yml
- .github/workflows/lint-pr-title.yml
- .github/workflows/remove-labels.yml
- PULL_REQUEST_TEMPLATE.md
- Add pull request template
- Add add/remove labels bots
- Add typo review bot
- Add lint PR title bot
> chore(bots): add review and labels bots

- .github/workflows/add-conflicts-label.yml
- .github/workflows/add-label.yml
- .github/workflows/assigned-label.yml
- .github/workflows/avoid-typos.yml
- .github/workflows/lint-pr-title.yml
- .github/workflows/remove-labels.yml
- Draft for testing adding permissions to workflows for avoiding this issue:
- Formatted workflows with prettier
- Resolve #
> chore(workflows): add permissions for workflows on PRs

- src/routes/auth/unlock/+page.svelte
- Update existing data-cy attributes broken after changing testid to hook
- Will use this branch to keep adding more attributes
- Resolve #
> add(testattr): fix existing test attr and add more as hook

- README.md
- Remove init submodules step from readme, since this is no longer required
- Resolve #
> chore(docs): remove submodules step from readme

- src/lib/elements/Checkbox.svelte
- src/lib/elements/Input/Input.svelte
- src/lib/layouts/Navigation.svelte
- src/lib/layouts/Sidebar.svelte
- src/lib/layouts/Slimbar.svelte
- src/lib/layouts/Topbar.svelte
- src/routes/chat/+page.svelte
- src/routes/friends/+page.svelte
- Add hook property for Input element to store test attribute
- Add various data-cy attributes for navigation, sidebar, slimbar and main screen
- Fixing warning on using export let hook
- Resolve #
> add(testid): add test ids for several ui elements working

- src/lib/components/profile/ProfilePicture.svelte
- src/lib/components/ui/Modal.svelte
- src/lib/elements/Text.svelte
- src/routes/auth/unlock/+page.svelte
- Add data-cy attributes for UI elements on select profile modal
- Add hooks for Profile Picture, Modal and Text elements for adding test attributes on UI elements for these types
- Resolve #
> add(attributes): add test attributes for chats sidebar

- src/lib/components/group/CreateGroup.svelte
- Add test attributes for create group modal
- Resolve #
> update(attributes): add attributes for create group modal

- src/lib/elements/Title.svelte
- src/routes/auth/new_account/+page.svelte
- Add test attributes for new create username screen
- Resolve #
> add(attributes): add tests attributes for create username screen

- src/lib/components/PinInput.svelte
- src/lib/state/Store.ts
- src/lib/state/initial.ts
- src/lib/utils/Logger.ts
- src/routes/chat/+page.svelte
> feat(Logger): Create internal logger

- package-lock.json
- package.json
- src/lib/wasm/WarpStore.ts
- yarn.lock
> update(Warp): Add test relay server

- src/lib/components/settings/OrderedPhrase.svelte
- src/lib/components/ui/FileUploadButton.svelte
- src/lib/elements/Checkbox.svelte
- src/lib/elements/Select.svelte
- src/lib/layouts/SettingSection.svelte
- src/routes/settings/profile/+page.svelte
- Add data-cy hook for properties of the following elements: Checkbox, SettingsSection, OrderedPhrase, FileUploadButton, Select
- Add data-cy test properties on elements from Settings Profile page
- Resolve #
> add(test): test attributes for settings profile page

- src/lib/components/ui/ContextMenu.svelte
- src/routes/friends/+page.svelte
- src/routes/settings/profile/+page.svelte
- Add test attributes for profile banner, copy id button and context menu options on Friends, add friend button
- Add hook on context menu UI element from src
- Resolve #
> add(attributes): add test attributes for banner and copy id buttons

- src/lib/elements/Toast.svelte
- src/routes/settings/profile/+page.svelte
- Add test attributes for toast notifications
- Add test attribute for select option
- Required for automated tests on settings profile
- Resolve #
> add(attributes): add attributes for toast and select of profile

- .github/workflows/automated-tests.yml
- Since most people is now using PR's and not just merging to dev, its a good time to start running cypress tests on every pr commit from the repo
- Draft for now until making sure it works correctly
- Resolve #
> add(ci): add cypress tests execution workflow on pr commits

- src/lib/enums/index.ts
- src/lib/lang/index.ts
- src/lib/state/settings/default.ts
- src/lib/state/settings/index.ts
- src/routes/settings/+layout.svelte
- src/routes/settings/accessability/+page.svelte
> chore(typos): fix typos

- src/lib/components/files/FileFolder.svelte
- src/lib/components/files/state.ts
- src/lib/types/index.ts
- src/lib/wasm/ConstellationStore.ts
- src/lib/wasm/HandleWarpErrors.ts
- src/routes/files/+page.svelte
> feat(Constellation): Add function to rename files

- src/lib/components/settings/Key.svelte
- src/lib/components/settings/Meter.svelte
- src/lib/components/settings/VideoTest.svelte
- src/lib/components/ui/Banner.svelte
- src/lib/components/ui/RelaySelector.svelte
- src/lib/elements/UnderConstruction.svelte
- src/routes/settings/about/+page.svelte
- src/routes/settings/audio_video/+page.svelte
- src/routes/settings/developer/+page.svelte
- src/routes/settings/extensions/+page.svelte
- src/routes/settings/keybinds/+page.svelte
- src/routes/settings/licenses/+page.svelte
- src/routes/settings/notifications/+page.svelte
- Add test attributes for creating automation tests on settings audio, extensions, keybinds, accessibility, notifications, about and developer
- Add test attributes for components: Key, Meter, VideoTest, Banner, RelaySelector, UnderConstruction
- Resolve #
> add(attributes): add test attributes for settings audio and extentsions

- src/routes/files/+page.svelte
- src/routes/settings/profile/+page.svelte
> chore(Files): remove unused code & added icon property.

- src/lib/components/ui/ContextMenu.svelte
- src/lib/state/Store.ts
- src/lib/state/initial.ts
- src/lib/utils/Logger.ts
- src/lib/wasm/ConstellationStore.ts
- src/lib/wasm/HandleWarpErrors.ts
- src/lib/wasm/MultipassStore.ts
- src/lib/wasm/TesseractStore.ts
- src/routes/+layout.svelte
- src/routes/auth/new_account/+page.svelte
- src/routes/chat/+page.svelte
- src/routes/developer/debug/voice/+page.svelte
- src/routes/friends/+page.svelte
- Fixes issue where `Logger` was missing functions when cache wasn't cleared. This was due to `Logger` being stored via `createPersistentState()` and deserialization not knowing about the functions it was supposed to have. The result was errors blocking execution whenever Logger was loaded from cache.
- Since `Logger` doesn't really need to actually persist anything, I made `Logger` export an instance of itself instead. 
- As a result, logging is simplified: `get(Store.state.logger).info("")` => `log.info("")`
- Also changed all `console.log` calls into `log.info` 
- Resolve #80
> fix(bug): logger functions missing

- package-lock.json
- package.json
- src/lib/wasm/RaygunStore.ts
- yarn.lock
- Implements the hooks for missing raygun features. Namely
- adding/removing group participants
- renaming chat
- sending and downloading files from message (only the hooks so e.g. downloading will not do anything when called since that returns a stream that needs to be processesd)
> feat(raygun): implement missing raygun hooks

- src/lib/enums/index.ts
> Lingo update

- src/lib/types/index.ts
- src/lib/wasm/ConstellationStore.ts
- src/routes/files/+page.svelte
> feat(Constellation): Implement download files

- src/lib/components/files/FileFolder.svelte
- src/lib/components/files/ImageFile.svelte
- src/lib/types/index.ts
- src/routes/files/+page.svelte
- src/routes/files/FolderItem.svelte
- fix long file names in sidebar to display ellipsis
- Resolve #
snip of specific app section... 
Tiny pr here. I was going to put in with drag and drop files but it started to get messy and figure put this in first since it's tiny
> fix(sidebar): add ellipsis to long file titles

- src/lib/components/utils/Emoji.ts
- src/lib/elements/Text.svelte
- src/lib/elements/renderer/HtmlRenderer.svelte
- src/lib/elements/renderer/TextRenderer.svelte
- src/lib/elements/renderer/index.ts
- Wraps the emojis in a`<p>` tag in chat messages
> feat(chat): wrap emojis

- src/lib/elements/Input/Input.svelte
- src/lib/elements/Input/markdown.scss
- Fixes text rendering outside chatbar textbox if too large
- Resolve #141
> update(fix): text out of bounds in chatbar

- src/lib/types/index.ts
> chore(typo): fix typo

- src/lib/wasm/MultipassStore.ts
- Fixes undefined usernames in chat
- Resolve #121
> fix(chat): fix undefined usernames in chat

- src/routes/friends/+page.svelte
- src/routes/settings/profile/+page.svelte
- copy button now copies DID by default instead of short id. (since short id can't be used for friend requests yet)
> fix(copydid): copy did by default instead of short id

- src/lib/components/ui/FileUploadButton.svelte
- src/lib/components/utils/CompressImage.ts
- src/routes/settings/profile/+page.svelte
…or banner picture
- Resolve #
> fix(Profile): Always compress image to be possible to upload it to profile picture or banner picture

- src/lib/components/settings/Key.svelte
- src/lib/components/ui/KeyboardListener.svelte
- src/routes/settings/keybinds/+page.svelte
Resolve keybinds not saving when pressing multiple keybinds.
> fix(Keybinds): Fix keybinds not saving properly.

- src/lib/wasm/WarpStore.ts
- Removes a relay address that was left in for debugging that was overlooked
> fix(relay): remove debug address

- .github/workflows/automated-tests.yml
- Add Playwright tests job in the automation tests CI workflow to run tests requiring the launch of more than one user instance
- For now, its only friend request send/accept automation test and account creation tests running on playwright
- Resolve #
> chore(playwright): add automated tests for playwright

- src/lib/lang/index.ts
- Update the description for create account page to match workflow
- Resolve #224
> fix(login): update create account description

- src/lib/layouts/login/NewAccount.svelte
- src/routes/friends/+page.svelte
> fix(CreateAccount): Let profile picture on create account as default

- .github/workflows/automated-tests.yml
- Should display a comment with summary of Playwright test results in PR's. Comment is autorefreshed on every commit. Comment will look like this:
- Resolve #
> chore(ci): add summary test results comment on PR

- src/lib/wasm/RaygunStore.ts
There are a few likely regressions on dev at the moment. This PR only fixes this error: `conversation.id is not a function`
> fix(regression): conversation.id is not a function

- src/lib/state/Store.ts
- Fix usercache not returning correct value if not present
> fix(cache): fix cache return undef

- package-lock.json
- src/lib/layouts/Controls.svelte
- src/lib/layouts/login/Entrypoint.svelte
https://github.com/user-attachments/assets/2602fabe-d292-4b61-862a-8a7908cd8e84
- Resolve #281
> fix(CreateNewAccount): Fix UI on create new account

- .github/workflows/automated-tests.yml
- src/lib/lang/index.ts
- Attempt to fix JSON report issue for CI automated tests, that is failing to generate when a test fails, and therefore comment with results cannot be posted because JSON report is missing
- Changed on purpose the text of font description to "force" a test to fail. This change is not intended to be added, so once that I figured out the issue, I will change back the text to its original message (please dont merge this pr until Draft label is removed)
- Resolve #
> chore(reporter): update JSON report to be posted on failure

- src/lib/state/auth/index.ts
- src/routes/+layout.svelte
- src/routes/+page.svelte
- src/routes/auth/+page.svelte
- Fix a problem with auto login/refreshing due to changes in #296
- It caused warp not being initialized when refreshing
- This change also makes it so we go directly to chat instead of unlock -> chat during auto login
- Potentially fixes following issues? (Depends on if those were created before or after #296)
- Fix #297
- Fix #298 
- Fix #299 
- Fix #300
> fix(auth): fix problem with auto login/refresh

- .github/workflows/automated-tests.yml
- Adding Allure Report for automated tests CI - The same that Sara implemented on the testing repo here: https://github.com/Satellite-im/automated-tests-web/pull/105
- Adding steps to add/remove Failed Automated Tests label on PR depending on resu;ts
- Resolve #
> add(reporter): add allure report for CI automated tests

- src/lib/layouts/Navigation.svelte
- src/lib/state/Store.ts
- src/routes/friends/+page.svelte
- Fix friend request needing to switch pages before updating
- Resolve #329
> update(fix): friend request not updating realtime

- src/app.scss
- src/lib/components/Polling.svelte
- src/lib/components/messaging/ChatPreview.svelte
- src/lib/components/messaging/Conversation.svelte
- src/lib/elements/Loader.svelte
- src/routes/chat/+page.svelte
> feat(Better Polling & loading): General fixes to polling and loading status for many components

- src/lib/layouts/Slimbar.svelte
> fix(Favorites): Fix profile picture on favorites

- src/lib/components/ui/CDNConfigurator.svelte
- src/lib/components/ui/GamepadListener.svelte
- src/lib/components/ui/IntegrationDisplay.svelte
- src/lib/components/widgets/BatteryIndicator.svelte
- src/lib/components/widgets/CPU.svelte
- src/lib/components/widgets/RamUsage.svelte
- src/lib/components/widgets/WidgetBar.svelte
- src/lib/elements/RangeSelector.svelte
- src/routes/files/+page.svelte
- src/routes/files/FolderItem.svelte
- src/routes/settings/developer/+page.svelte
- src/routes/settings/gamepad/+page.svelte
- src/routes/settings/messages/+page.svelte
- src/routes/settings/preferences/+page.svelte
- src/routes/settings/profile/+page.svelte
- src/routes/settings/realms/+page.svelte
- Removing duplicated Settings Section in Settings Developer
- Adding test attributes for Settings Pages not added before (mostly new settings added recently)
- Adding test attributes missing for Files Page
- Resolve #
> add(test): test attributes for settings pages and files

- src/lib/components/messaging/Conversation.svelte
- src/routes/chat/+page.svelte
> fix(Chats): Fixed syncing chats and call control when no chats

- src/lib/components/ui/Toasts.svelte
- src/lib/elements/Toast.svelte
- src/lib/state/Store.ts
- src/lib/state/ui/toast.ts
- src/lib/wasm/MultipassStore.ts
- src/lib/wasm/RaygunStore.ts
- src/routes/friends/+page.svelte
- src/routes/wallet/+page.svelte
- Implements clickable toasts. Adds click handler for 
-  incoming messages (directing to the chat)
- incoming friend requests (direct to friend page)
- Resolve #337
> feat(toast): impl clickable toasts

- src/routes/settings/profile/+page.svelte
> fix(Profile): Avoid save changes when click on cancel button on profile page

- src/lib/components/Polling.svelte
- src/lib/components/messaging/ChatPreview.svelte
- src/lib/components/ui/ChatFilter.svelte
- src/lib/elements/Input/Input.svelte
- src/lib/lang/en.json
- src/lib/layouts/Chatbar.svelte
- src/lib/layouts/Slimbar.svelte
- src/lib/mock/users.ts
- src/lib/state/conversation/index.ts
- src/lib/state/db/persistedState.ts
- src/lib/state/ui/index.ts
- src/lib/types/index.ts
- src/lib/wasm/RaygunStore.ts
- src/routes/chat/+page.svelte
- Implements the typing indicator fully for chats
- Icon will change to indicate someone is typing
- Below the chatbar a message will appear with the people who are typing
- Resolve #336
When typing an event is send to warp via wasm. That process logs an error with something along the line of `recursive function` etc but this error does not impact the functionality.
We can try to resolve this at a later time though. Considering (while this case happens all the time here and thus is reproducable) it happens quite a lot at other times too so they could all have the same root cause.
> feat(chats): Typing indicator

- src/lib/media/Voice.ts
> chore(typo): fix typo on log

- src/lib/layouts/Profile.svelte
- Hide's send btc on profile as requested on https://github.com/Satellite-im/UplinkWeb/issues/330
How to test:
-  send btc on profile should not appear
> chore(btc): hide send btc section

- src/lib/components/messaging/message/MessageReactions.svelte
- Adds a highlight when user reacts to a message with an emoji
- Resolve #334
> feat(chat): add reaction indicator

- src/lib/components/Polling.svelte
- src/lib/components/messaging/ChatPreview.svelte
- src/lib/components/ui/ChatFilter.svelte
- src/lib/elements/Input/Input.svelte
- src/lib/lang/en.json
- src/lib/layouts/Chatbar.svelte
- src/lib/layouts/Slimbar.svelte
- src/lib/mock/users.ts
- src/lib/state/conversation/index.ts
- src/lib/state/db/persistedState.ts
- src/lib/state/ui/index.ts
- src/lib/types/index.ts
- src/lib/wasm/RaygunStore.ts
- src/routes/chat/+page.svelte
Reverts Satellite-im/UplinkWeb#364
> Revert "feat(chats): Typing indicator"

- src/routes/settings/profile/+page.svelte
- Fix https://github.com/Satellite-im/UplinkWeb/issues/378
https://github.com/user-attachments/assets/30a05179-bd22-459b-bf28-80507a392468
> fix(bug): fix copy seed

- src/routes/chat/+page.svelte
> fix(chat): fix typing indicator

- src/lib/state/ui/index.ts
- Fix typing indicator not updating for active chat
> fix(chat): fix active chat not updating

- src/routes/files/+page.svelte
https://github.com/user-attachments/assets/ceba3349-a64a-4ad8-aa63-291e6724562a
- Resolve #366
> fix(Files): Fix files not appearing after a refresh

- src/lib/state/Store.ts
- src/lib/state/ui/index.ts
- src/routes/friends/+page.svelte
https://github.com/user-attachments/assets/fc8f29bf-ae74-46be-9030-bbf4d374b945
- Resolve #399
> feat(Chat): Possible to unhide chats

- src/lib/wasm/MultipassStore.ts
- src/lib/wasm/RaygunStore.ts
- add extra check for multichat notification
- Resolve #315
It looks like the unreads are not currently hooked up, I'll be investigating where and why
> fix(notification): add extra check for multichat notification

- package.json
- src/lib/components/files/FileFolder.svelte
- src/lib/types/index.ts
- src/routes/files/+page.svelte
> feat(Storage): Show images thumb on files

- package.json
- Add friends should work again properly
> chore(revert): revert wasm version

- README.md
- Update docs
How to test:
Going to https://github.com/Satellite-im/UplinkWeb/blob/10b32228e543437973156bfea74c6a0eb7e21ed0/README.md should display fine
> chore(docs): minor update

- src/lib/components/calling/VideoPreview.svelte
> fix(Call): Fix float video on screen

- src/lib/components/calling/VideoPreview.svelte
> fix(Call): Fix float video when user deactivate it

- package.json
`@shopify/draggable` does not seem to be used anywhere
How to test:
- everything needs to be the same, including dragging stuff like folders and files etc
> chore(package): ditch package

- src/lib/components/messaging/ChatPreview.svelte
- src/lib/state/conversation/index.ts
- Fix time display in sidebar for last message
- Resolve #413
> fix(chat): fix sidebar time

- src/lib/elements/Input/Input.svelte
- src/lib/layouts/Chatbar.svelte
- src/routes/chat/+page.svelte
- Fix input event not delegated and reduce debounce timer. Fixes the typing indicator
- Resolve #453
- Resolve #412
> fix(chat): Typing fix

- src/lib/media/Voice.ts
> fix(Compile): Fix compilling error message

- src/lib/elements/Checkbox.svelte
- src/lib/lang/en.json
- src/lib/state/auth/index.ts
- src/lib/wasm/TesseractStore.ts
- src/lib/wasm/WarpStore.ts
- src/routes/auth/+page.svelte
- src/routes/settings/profile/+page.svelte
Reverts Satellite-im/UplinkWeb#434
> Revert "feat(settings): Seed phrase save"

- src/lib/elements/Checkbox.svelte
- src/lib/lang/en.json
- src/lib/state/auth/index.ts
- src/lib/wasm/TesseractStore.ts
- src/lib/wasm/WarpStore.ts
- src/routes/auth/+page.svelte
- src/routes/settings/profile/+page.svelte
Same as https://github.com/Satellite-im/UplinkWeb/pull/434
> feat(settings): Seed phrase save

- src/lib/components/group/CreateGroup.svelte
- src/lib/components/messaging/message/MessageReactions.svelte
- Add data-cy/hook test attributes for emoji reaction containers on chats
- These will be used to add automated tests for these features
- Resolve #
> add(attributes): test attributes for emoji reactions

- src/routes/friends/+page.svelte
Fixes https://github.com/Satellite-im/UplinkWeb/issues/490
before
https://github.com/user-attachments/assets/8e8da0ee-c8fa-494e-8934-9db413b5771d
after
https://github.com/user-attachments/assets/905c601d-6ccc-4c64-b384-24f6ec449728
> fix(groups): fix chats icon on friends page

- src/lib/types/index.ts
- Fix this warning
how to test:
- npm run check
- the above error should not appear and should behave the same as dev
> chore(warning): fix chat settings warning

- src/lib/components/wallet/CreateTransaction.svelte
- src/lib/utils/Wallet.ts
- Enables input of amounts in expected decimal format instead of only by smallest decimal unit
- Improves input validation of amount
- Accurately converts input string directly to bigint, avoiding undesirable floating point imprecision with number
- Resolve #474
> fix(crypto): decimal amount conversion to bigint

- src/lib/media/Voice.ts
- src/routes/+layout.svelte
- Fixes https://github.com/Satellite-im/UplinkWeb/issues/502
> fix(keybind): keybinds triggering sounds outside of calls

- src/lib/mock/users.ts
- Fix the following warning
How to test
- npm run check
- the above error should not appear and should behave the same as dev
> chore(warning): fix integrations warning

- src/lib/components/group/CreateGroup.svelte
- src/lib/lang/en.json
- Fixes https://github.com/Satellite-im/UplinkWeb/issues/492
before
https://github.com/user-attachments/assets/96945d41-26a7-41f9-8cae-431174b4a6a9
after
https://github.com/user-attachments/assets/9b5f2234-1fcb-459b-a2bd-a47e559f0756
> fix(groups): display error if no group name is added

- src/lib/components/calling/CallSettings.svelte
- Fixes https://github.com/Satellite-im/UplinkWeb/issues/454
before
https://github.com/user-attachments/assets/3d2d6c21-6722-48ac-a56e-745555d539b6
after
https://github.com/user-attachments/assets/a3a713c6-aa39-406b-a173-074bc43646e5
> fix(call): fix call settings modal

- src/lib/components/group/ViewMembers.svelte
- Fixes https://github.com/Satellite-im/UplinkWeb/issues/499
before
https://github.com/user-attachments/assets/758a28e0-eff6-4a0b-b8e8-1f131b4f45fa
after
https://github.com/user-attachments/assets/c0e63dab-aaf3-456d-b967-a310e6d38674
> fix(groups): fix group modal list members

- src/lib/state/Store.ts
- Fixes https://github.com/Satellite-im/UplinkWeb/issues/470
before
https://github.com/user-attachments/assets/23382d9c-37bd-4208-8651-3518a46f1cda
after
https://github.com/user-attachments/assets/d519efcb-2aec-4666-b951-90a9471edc05
> fix(profile): fix integrations

- src/lib/components/ui/RelaySelector.svelte
- Fixes network page page refresh. Its prob caused by an import order making some variables not initialized during access time. I made it instead to import it lazily 
- Resolve  #512
> fix(settings): Fix network page

- src/lib/components/ui/EmojiGroup.svelte
- src/lib/layouts/Chatbar.svelte
- src/lib/state/ui/index.ts
- src/routes/chat/+page.svelte
- Implements the functionality of the plus button in reactions
- Resolve #482
> feat(chat): Impl emoji button in reaction

- src/lib/components/messaging/embeds/FileEmbed.svelte
- src/lib/components/messaging/embeds/ImageEmbed.svelte
- src/routes/chat/+page.svelte
- Add test attributes for chat-messages embeds file and images and other chat elements used for markdowns
- Resolve #
> add(attrs): add test attributes for embeds and messages chats

- src/routes/files/+page.svelte
> chore(grammar): update copy

- src/lib/wasm/HandleWarpErrors.ts
> chore(copy): update copy

- src/routes/files/+page.svelte
> chore(files): fix list layout

- README.md
> chore(docs): minor grammar update

- src/lib/lang/en.json
- src/routes/settings/profile/+page.svelte
- Hides the seed buttons in settings when the seed is missing
- Resolve #481
> feat(settings): hide seed button if missing

- src/lib/wasm/HandleWarpErrors.ts
> fix(Constellation): Fix message when create item with same name

- src/lib/components/messaging/ChatPreview.svelte
- src/lib/components/messaging/stickers/StickerSelector.svelte
- src/lib/layouts/Chatbar.svelte
- src/lib/utils/CommonVariables.ts
- src/routes/chat/+page.svelte
https://github.com/user-attachments/assets/b28ed2d7-8d99-4263-819d-43d1347a356b
- Resolve #397
> feat(Stickers): Send stickers and gifs on chat

- src/lib/layouts/Chatbar.svelte
https://github.com/user-attachments/assets/2a3eef77-4c7d-435f-a76d-7007af386257
- Resolve #
> fix(ChatBar): Rebuild chatbar to align placeholder text

- src/lib/state/conversation/index.ts
- src/lib/types/index.ts
- src/lib/wasm/RaygunStore.ts
https://github.com/user-attachments/assets/5e64d872-6b87-43ab-8d2a-f14863fe343f
- Resolve #546
> fix(Chat): Update last message on chat preview when it is edited or removed

- src/routes/chat/+page.svelte
> fix(Chat): Fix remove emoji reaction from message

- src/lib/lang/en.json
> chore(locale): fix locale

- src/lib/layouts/Sidebar.svelte
> chore(marketplace): hide button

- src/lib/components/ui/InstallBanner.svelte
- Add test attributes for install desktop uplink banner
- Resolve #
> add(test): add test attribute for banner

- src/lib/state/wasm/relays.ts
- adds the new wss secure relay.
- Resolve #
We will need to make all new accounts.
> update(relay): new relay for wss

- src/lib/lang/en.json
- src/lib/layouts/Chatbar.svelte
- Add ui for reply in chatbar
- Resolve #433
> feat(chat): Reply UI

- src/lib/components/ui/InstallBanner.svelte
chore(copy): macOS instead of MacOS
> chore(copy): macOS instead of MacOS

- src/lib/wasm/ConstellationStore.ts
- Fix goback button sometimes not working
- Resolve #568
> fix(files): fix path validation for back action

- .github/workflows/add-label.yml
> chore(ci): update version

- .github/workflows/generate-apk.yml
> chore(ci): update versions

- .github/workflows/run-build.yml
> chore(ci): minor update

- .github/workflows/build-desktop.yml
- Attempt to build desktop versions for macos, ubuntu and windows on CI for each PR
- Resolve #
> add(ci): build desktop installers

- .github/workflows/generate-apk.yml
- src/routes/chat/+page.svelte
-  Remove edit when message is sticker or gif
- Resolve #588 
- Resolve #476
> fix(Chat): Remove edit when message is sticker or gif
