src/lib/components/inventory/InventoryItem.svelte, src/lib/components/profile/ProfilePicture.svelte, src/lib/components/ui/ColorSwatch.svelte, src/lib/components/ui/PopupButton.svelte, src/routes/settings/inventory/+page.svelte, src/routes/settings/messages/+page.svelte, src/routes/settings/preferences/+page.svelte
- Adding hook property for test attributes on InventoryItems, ProfilePicture, ColorSwatch, PopUpButton kit elements
- Adding data-cy attributes for elements on Settings Inventory, Settings Customization and Settings Mesages
- Resolve #
=> add(attributes): add hooks and data-cy attributes for settings pages

src/lib/components/ui/ContextMenu.svelte
- Cleaning up the hook attribute for context menu options to use item.id instead of item.name converted to lower case and using regex to add separators. No need to do that since we can just simply use item.id for it
- Resolve #
=> update(attribute): update test attribute for context menu options

package-lock.json, package.json, yarn.lock
- Adding svelte-check to find errors and warnings in the code
- Errors found are not addressed on this PR, the goal is once that there are no errors we can add a pre-commit hook using  this check
- You can do `npm run check` to run svelte-check which will show an output like this:
- Also, you can now run `npm run lint` to run prettier and then svelte-check
- Resolve #
=> chore(lint): add svelte-check to find errors

src/lib/wasm/MultipassStore.ts
Resolves this error in the console which appears on account creation:
```
[ERROR] (9:21:52 AM):  Error creating identity: Error: Length for 'status' is invalid. Current length: 0. Minimum Length: Some(1), Maximum: Some(512)
```
- Resolve #
=> chore(fix): fix error on empty status message

src/lib/wasm/WarpStore.ts
- `minimal_testing` is only in-memory. That's why we couldn't log back into an existing account. `minimal_basic` enables persistence
- Note that there are errors solved by #114 that make it easier to test this PR if it gets merged first.
- Resolve #
=> fix(wasm): enable warp persistence

src/lib/components/ui/RelaySelector.svelte, src/lib/elements/Input/Input.svelte, src/lib/state/wasm/relays.ts
- Adds the default relay from warp `RelayClient`.
- Default relays cannot be edited or removed but can be turned off
- Make buttons align to the inputs in the ui
- Fix input click on copy not working
=> feat(wasm): add default relays

src/routes/+layout.svelte, src/routes/settings/profile/+page.svelte
=> fix(Profile): Fix undefined status message and username on profile page

src/lib/elements/Input/Input.svelte
- ChatBar has not been cleared after we send message using send button, just with enter. So now, when we hit a button, it will send message and clear input. This was happening because rich variable that is true on chatbar, so code just guarantee that will be updated as well when value has changed.
- Resolve #
=> fix(Input): Clear input when rich option is enabled and we click on send button

src/lib/components/ui/ContextMenu.svelte, src/lib/types/index.ts, src/routes/settings/profile/+page.svelte
- Resolve #250 
- Resolve #249 
- - Resolve #244
=> fix(Profile): Clear profile picture and back to default one

src/lib/wasm/RaygunStore.ts
- Fixes conversations breaking after refresh. 
1) `raygun.raygun_subscribe()` being called before `raygun.list_conversations()` was causing it to hang. This shouldn't happen and we don't know why it happens, and I could not reproduce it on in simple js script. However, reversing the order they are called allows uplinkweb to work properly. I've left a comment in the code about it, until we can figure out the root cause.
2) `conversation.inner.id()` is a function in rust that returns a string. when it gets compiled to wasm it is still a function, as can be seen in the generated typescript. But somehow the browser only recognizes it as a field and otherwise throws an error that the function doesn't exist. changing it to use it as a field allows it to work in the browser, although in your …
=> fix(Conversations): Fix conversations breaking after refresh

.github/workflows/automated-tests.yml
- Removing cypress job from automated test results workflow, since all tests have been already ported to playwright
- Resolve #
=> chore(ci): remove cypress job from automated tests

src/lib/state/Store.ts, src/lib/wasm/MultipassStore.ts, src/routes/auth/+page.svelte, src/routes/settings/profile/+page.svelte
- Fixes user profile picture and banner being reset when something changes in settings. (e.g. by editing the status message)
- Resolve #332
=> fix(settings): Fix banner/profile reset on changes

src/routes/chat/+page.svelte
- Fixes an error with preview chat context menu showing chat.gide instead of "Hide" (just a typo in code)
currently in dev:
with this pr:
- Resolve #
=> update(fix): fix chat preview context menu text for hide chat

src/lib/components/inventory/InventoryItem.svelte, src/lib/lang/en.json, src/routes/settings/profile/+page.svelte
Previously when selecting a generic integration type, it would have an input below the select box, this change inlines that input and labels it as well so things look a bit cleaner.
Before:
After:
=> fix(Styling): Fix weird styling for generic integration kinds

.github/workflows/automated-tests.yml
- Sometimes the CI publish report job fails (we are still investigating the reason why) and the Failed Automated Tests label is added. Since the tests themselves are already passed, there is no need to add this label when publish report fails.
- Resolve #
=> chore(ci): dont add failed label on publish report issues

src/app.scss, src/lib/components/community/settings/roles/Role.svelte, src/lib/components/inventory/InventoryItem.svelte
- Fix the following warnings when using `npm run build`
How to test:
- `npm run build`
- the ones marked as red should not appear and the app should have the same behavior
=> fix(warnings): fix warnings on prod build

.vscode/settings.json, src/lib/components/calling/CallScreen.svelte
=> fix(Call): Close settings and volume menu on call when click outside

.github/workflows/run-build.yml, src/app.scss
Adds CI for the following:
- `npm run build` on `dev` branch and grabs log
- `npm run build` on PR branch and grabs log
- compares both logs to see if there is additional warnings
- adds comment on the PR with the additional warning
=> chore(ci): run build preview and compare logs

src/lib/wasm/HandleWarpErrors.ts
- Fix the following warning
How to test
- npm run check
- the above error should not appear and the behavior should be the same as dev
=> chore(warning): fix warp warning

src/lib/elements/Button.svelte, src/lib/enums/index.ts, src/lib/lang/en.json, src/routes/chat/+page.svelte
- Add tooltips for buttons displayed on top from chat (audio, video call, favorite, pinned, show members, settings)
- Add tooltip for send coin button
- Updated enum for tooltip position to allow passing bottom option
- Updated ButtonSvelte to allow using tooltip bottom css
After:
https://github.com/user-attachments/assets/413dac25-e760-4230-a282-8ffff0364257
- Resolve #
=> add(tooltips): add missing tooltips on chat page

src/routes/chat/+page.svelte
https://github.com/user-attachments/assets/c9206026-952c-4956-b3cb-2b3d461c298d
- Resolve #
=> fix(Sidebar): Sort chats on sidebar according with datetime last message sent or received

src/routes/chat/+page.svelte
https://github.com/user-attachments/assets/728cbf5c-a78b-45aa-904a-27b0dd9d6807
- Resolve #495
=> fix(Chat): Fix remove reaction when user select exactly the same emoji

README.md
chore(docs): add info about mobile
=> chore(docs): add info about mobile

src/app.scss, src/variables.scss
- The dropdown menus on Windows have looked messed up for a while. The background coloring has always been white despite changing themes, while the text changes color with the theme. Now the Background of the dropdown menus mirror the background of the app. I have not tested on Mac or Linux.
- Resolve #N/A
=> fix(UI): Fix Windows Dropdown Background

src/lib/components/messaging/emoji/EmojiSelector.svelte
- Let emojis aligned to the left when filtered
- Resolve #589
=> fix(Emoji): Let emojis aligned to the left when filtered
